name: Build and Deploy Eaglercraft

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Make client bundle
        run: cd target_teavm_wasm_gc && ./MakeWASMClientBundle.sh

      
      - name: Copy src folder to deploy folder
        run: cp -r src target_teavm_wasm_gc/javascript/

      - name: Deploy to Pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: target_teavm_wasm_gc/javascript
          clean: true
          
